---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-example-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: "https://github.com/argoproj/argocd-example-apps.git"
  type: "git"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: ansible
spec:
  project: default
  source:
    repoURL: "https://github.com/argoproj/argocd-example-apps.git"
    path: guestbook
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
